### PR TITLE
Feature/aos2 17 footer component

### PR DESCRIPTION
**Pull request by krivanek06**
Migrated footer into its own component. 
Jira task: https://bitovi.atlassian.net/browse/AOS2-17
- [x] - make selector use 'footer' and not 'app-footer' for accessibility
- [x] - migrate app styles to global styles as needed
- [x] - remove CowComponent

when I used only `footer` instead of `app-footer` - I was receiving the error `ERROR RangeError: Maximum call stack size exceeded`, so I left it with the selector `app-footer`

### CODE REVIEW

**Review by alexanderwiebe — APPROVED** [review]
Looks good to me

**Review by m-thompson-code — CHANGES_REQUESTED** [review]
I'm assuming because you're trying to put footer inside of footer haha. I'd remove the inner footer

**Comment by m-thompson-code** [comment]
lgtm +1

**Review by m-thompson-code — APPROVED** [review]
merging

**Pull request merged**
